### ISSUE TITLE
Away mode missing

### ISSUE THREAD

**Issue by KThaulow** [toringer/home-assistant-heru#12]
Thanks for your work on this!

## Version of the custom_component

Version 0.1.9

## Configuration
Followed the wizards at and downloaded through HACS

## Describe the bug
Everything works but the “Away Mode” is missing. It’s shown in the documentation screenshots so I wonder why I don’t have it. See image here 

![IMG_0723](https://github.com/toringer/home-assistant-heru/assets/5908668/6d1bc3aa-665f-4058-900f-208642ff93be)

**Comment by toringer** [comment]
Ups, that switch was accidentally removed from the component some time ago. I can add it back in if you need it.

**Comment by KThaulow** [comment]
That would be great, thank you so much!

**Comment by toringer** [comment]
Added in v0.2.0
