### ISSUE TITLE
Cooler & Filter adaptive pressure adjustments are missing thier controls Any plans for these?

### ISSUE THREAD

**Issue by friskens** [toringer/home-assistant-heru#23]
**Is your feature request related to a problem? Please describe.**
No and yes, seems they are just an oversight on the developers side.

**Describe the solution you'd like**
A button and the associated alarms for the cooler accessory and for the adaptive pressure measurment device for filter changes.

**Describe alternatives you've considered**
Doing it myself, but serious lack of time due to too much HA work already.

**Additional context**
I have a Heru 160 T with cooler and also the filter degradation pressure detection device, due to cats, lots of cats.

**Comment by magicus** [comment]
Do you know the modbus addresses of these controls?

**Comment by friskens** [comment]
alarms:
1x00032 Cooling alarm
Settings:
4x00068 Cooler type 0 1 0 = None, 1 = Water
4x00069 Cooler enabled 0 1 0 = no, 1 = yes

Then it's this mess for the filter and it seems also alot of other pressure sensors...
![image](https://github.com/toringer/home-assistant-heru/assets/152422800/09679b6b-1c01-44e0-8f8c-e26e7affc838)

**Comment by magicus** [comment]
> In general, I do not want to implement settings that on the IQC display has the warning "Warning. Only for qualified technicians". 

Sounds like a good approach!

**Comment by friskens** [comment]
Alright I ofc respect your hesitation of implementing the filter sensor, note however that those settings is either for a Modbus attached sensor indentifying as such or a specific other physical connection that measures 0-10V between two connectors, can't really mess any hardware up only make the unit act strange I guess... Much grateful for your cooler on off implementation looking forward too it this summer! Right now i have to set it to run manually...

**Comment by friskens** [comment]
Accidentally closed sigh

**Comment by friskens** [comment]
@toringer so could at least cooler on/off and the alarm be sorted?

**Comment by toringer** [comment]
Switch and alarm added in v1.0.5
