### ISSUE TITLE
Debug code in VSCode dev container

### ISSUE THREAD

**Issue by KThaulow** [toringer/home-assistant-heru#36]
## Version of the custom_component

Latest version of master

## Configuration
Describe your configuration here.

VSCode on M2 (Apple Silicon)

## Describe the bug
Thank you for this great integration!
I'm trying to contribute to the code, but I'm unable to attach the debugger to the task. 

The steps I'm using:
1. Fork the repo and start the dev container
2. Run the task "Run Home Assistant on port 8123"
3. Call "Remote Python Debugger: Start" in HA Service Calls
4. In the terminal, I'm not getting "It seems that frozen modules are being used..."

When running the "Python: Attach Local" launch, the debugger starts but I'm unable to hit any breakpoints. E.g. a breakpoint under `custom_components/heru/switch.py`. When modifying the code and restarting the task, I can see that the debug logs are getting updated with the new code. 

I suspect that the code that is being run is the copied code under `.devcontainer/hass/custom_components/heru/switch.py` instead of `custom_components/heru/switch.py`. 

I've tried to update the .devcontainer to use:
`"image": "mcr.microsoft.com/vscode/devcontainers/python:0-3.11-bullseye"`
and `"remoteUser": "vscode"` but that didn't help.

Can you help me figure out what I'm missing to be able to debug the code?

Thanks!

## Debug log

```text

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
2024-04-26 09:21:12.201 WARNING (MainThread) [homeassistant.components.debugpy] Waiting for remote debug connection on 0.0.0.0:5678
2024-04-26 09:21:21.974 WARNING (MainThread) [homeassistant.setup] Setup of debugpy is taking over 10 seconds.

```

**Comment by toringer** [comment]
Have the same problem myself, even after updating the devcontainer to the latest HA and python 3.12.

Found [this](https://github.com/home-assistant/core/issues/110623), but not sure if it is related.

**Comment by KThaulow** [comment]
I also found that post, but I'm not sure how to proceed from here. 

I tried to launch your code directly in the debugger instead of attaching the debugger, by adding this to `launch.json`

```
{
      "name": "Home Assistant",
      "type": "debugpy",
      "request": "launch",
      "module": "homeassistant",
      "justMyCode": false,
      "args": [
        "--debug",
        "-c",
        "config"
      ]
    }
```

However, I'm getting errors when doing so:
```
Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: '/usr/local/lib/python311.zip'
```

I'm fairly new to HA and dev containers, but I'll see if I can get that working instead.
