### ISSUE TITLE
Energy consumption

### ISSUE THREAD

**Issue by christian-nils** [toringer/home-assistant-heru#5]
Hi!

Thanks for the integration. It would be nice to have the energy consumption in the integration. I will try to implement it and do a PR.

/CN

**Comment by christian-nils** [comment]
Thanks for asking. You are right, the energy consumption is not available on the registries, but we know the PWM value for the fans, the same for the heater, etc. So we could make the assumption that the energy consumption could be written as:

instantaneous_power(W) = supply_fan_power * P_fan/(2*100) + exhaust_fan_power * P_fan/(2*100) + heater_power * P_heater/100 + P_control_board + P_rotor * abs(heat_cold_recovery_power/100)

I know that it will not be the exact value, but maybe that is still something interesting to expose to the user.

The P_* values depend on the unit model.

If you don't want to integrate this, please feel free to close the issue!

**Comment by toringer** [comment]
For sure a nice addition 👍

**Comment by christian-nils** [comment]
Alright, I tried my best over the night to implement it, here is the PR #7 , let me know if there is anything to improve.
